[*]
desktop_bg=#D6D3DE
desktop_shadow=#D6D3DE
desktop_fg=#E8E8E8
desktop_font=Nunito Sans Medium 13
wallpaper=/home/sl01220/Pictures/wp10211536-arasaka-wallpapers.png
wallpaper_mode=crop
show_home=0
show_trash=0
show_mounts=0
folder=/home/sl01220
